language: csharp
mono: none
dotnet: 2.0.2
before_install:
  - dotnet restore
install:
  - dotnet build ./src/main
  - dotnet build ./src/IntegrationTest
  - dotnet build ./src/test
script:
  - dotnet test ./src/test
  - dotnet test ./src/IntegrationTest
